BEGIN
    DECLARE contador INT DEFAULT 0;
    WHILE contador < 20 DO
        INSERT INTO asesores(
            tipo_documento,
            numero_documento,
            nombre,
            edad,
            genero,
            estado_civil,
            tipo_vivienda,
            estrato,
            num_hijos,
            personas_cargo,
            correo,
            telefono,
            nivel_estudios,
            experiencia_general,
            area_experiencia,
            tiempo_ventas,
            experiencia,
            otra_area_experiencia,
            perfil_natural_r,
            perfil_natural_e,
            perfil_natural_p,
            perfil_natural_n,
            perfil_natural_a,
            perfil_natural_r_ie,
            perfil_natural_e_ie,
            perfil_natural_p_ie,
            perfil_natural_n_ie,
            perfil_natural_a_ie,
            intensidad_perfil_natural,
            energia_natural,
            perfil_adaptado_r,
            perfil_adaptado_e,
            perfil_adaptado_p,
            perfil_adaptado_n,
            perfil_adaptado_a,
            perfil_adaptado_r_ie,
            perfil_adaptado_e_ie,
            perfil_adaptado_p_ie,
            perfil_adaptado_n_ie,
            perfil_adaptado_a_ie,
            toma_decisiones_adaptado,
            intensidad_perfil_adaptado,
            energia_adaptado,
            equilibrio_de_energia,
            modificacion_perfil,
            tiempo_formulario,
            unidad_tiempo,
            color,
            nombre_perfil,
            eje_dominante,
            perfil
        )
        VALUES (
            CASE WHEN RAND() < 0.5 THEN 'Cedula de ciudadanía' ELSE 'Cedula de extranjería' END,
            FLOOR(100000000 + RAND() * 900000000),
            CONCAT('Usuario', contador),
            DATE_SUB(NOW(), INTERVAL FLOOR(18 + RAND() * 50) YEAR),
            CASE WHEN RAND() < 0.33 THEN 'Masculino' WHEN RAND() < 0.66 THEN 'Femenino' ELSE 'Prefiero no decirlo' END,
            CASE WHEN RAND() < 0.2 THEN 'Soltero/a' WHEN RAND() < 0.4 THEN 'Casado/a' WHEN RAND() < 0.6 THEN 'Union libre' WHEN RAND() < 0.8 THEN 'Separado/a' ELSE 'Divorsiado/a' END,
            CASE WHEN RAND() < 0.33 THEN 'Familiar' WHEN RAND() < 0.66 THEN 'Propia' ELSE 'Alquilada' END,
            FLOOR(1 + RAND() * 6),
            FLOOR(RAND() * 5),
            FLOOR(RAND() * 5),
            CONCAT('usuario', contador, '@ejemplo.com'),
            CONCAT('3', FLOOR(10000000 + RAND() * 90000000)),
            CASE WHEN RAND() < 0.25 THEN 'Bachillerato' WHEN RAND() < 0.5 THEN 'Formación Técnica/Tecnologo' WHEN RAND() < 0.75 THEN 'Formación profesional - Pregrado' ELSE 'Posgrado' END,
            CASE WHEN RAND() < 0.2 THEN 'Sin experiencia' WHEN RAND() < 0.4 THEN 'Menor a 1 año' WHEN RAND() < 0.6 THEN 'Entre 1 y 2 años' WHEN RAND() < 0.8 THEN 'Entre 2 y 4 años' ELSE 'Mayor a 5 años' END,
            CASE WHEN RAND() < 0.2 THEN 'Sin experiencia' WHEN RAND() < 0.4 THEN 'Ventas' WHEN RAND() < 0.6 THEN 'Servicios de atención' WHEN RAND() < 0.8 THEN 'Recuperación y recobro' ELSE 'Back Office (BO)' END,
            CASE WHEN RAND() < 0.2 THEN 'Sin experiencia' WHEN RAND() < 0.4 THEN 'Menor a 1 año' WHEN RAND() < 0.6 THEN 'Entre 1 y 2 años' WHEN RAND() < 0.8 THEN 'Entre 2 y 4 años' ELSE 'Mayor a 5 años' END,
            CASE WHEN RAND() < 0.2 THEN 'Sin experiencia' WHEN RAND() < 0.4 THEN 'Menor a 1 año' WHEN RAND() < 0.6 THEN 'Entre 1 y 2 años' WHEN RAND() < 0.8 THEN 'Entre 2 y 4 años' ELSE 'Mayor a 5 años' END,
            CASE WHEN RAND() < 0.2 THEN 'Áreas administrativas' WHEN RAND() < 0.4 THEN 'Servicio al cliente presencial' WHEN RAND() < 0.6 THEN 'Venta al cliente presencial' ELSE 'Otros' END,
            NULL, 
			NULL, 
			NULL, 
			NULL, 
			NULL, 
			NULL, 
			NULL, 
			NULL, 
			NULL, 
			NULL,
			NULL,
			NULL, 
			NULL, 
			NULL, 
			NULL, 
			NULL, 
			NULL, 
			NULL, 
			NULL, 
			NULL,
			NULL,
			NULL, 
			NULL, 
			NULL, 
			NULL, 
			NULL, 
			NULL,
			NULL,
			NULL, 
			NULL, 
			NULL,
			NULL,
			NULL
        );
        SET contador = contador + 1;
    END WHILE;
END